[package]
name = "simple_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.1", features = ["postgres", "serde_json"] }
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }